
FROM eclipse-temurin:17-jdk-jammy as builder

WORKDIR /opt/app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
COPY ./src ./src
RUN ./mvnw spring-javaformat:apply

RUN ./mvnw clean install

